### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by BDubz20** [jhansche/ha-teslafi#11]
New issue when adding my Model Y.  It doesn't seem to matter if I add it as a first or second Tesla using this integration so makes me think it's an issue with some data that is being returned from the API for the Model Y.  

This started after 2.1 release fixing the memory leak.  

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 11:46:16 PM (2 occurrences)
Last logged: 11:47:41 PM

Error setting up entry SpaceY for teslafi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslafi/__init__.py", line 59, in async_setup_entry
    coordinator.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 787, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslafi/device_tracker.py", line 46, in extra_state_attributes
    int(h)
ValueError: invalid literal for int() with base 10: ''

**Comment by jhansche** [comment]
That line is trying to set the `heading` (degrees) by parsing it to an int. https://github.com/jhansche/ha-teslafi/blob/0f7443e8b3e12d1246acd966b7a9659ccfd4c412/custom_components/teslafi/device_tracker.py#L45
We check if it's present at all, but not checking it it's present but empty.

If you check the app Location section, does it show the red marker pointing in a particular direction? That direction it's pointing should be the heading we're trying to set.

Should be an easy fix: replace the `if h is not None` check with a simple truthy check: `if h`.

That part of the code didn't change in 2.1, so I don't think it was recently introduced. Maybe it's been asleep for a while, and right now TeslaFi just doesn't have the data. Can you try waking the car via the app, and then check it TeslaFi has updated location data, before re-adding it? 🤔

**Comment by BDubz20** [comment]
Thanks for looking into this.  I do have a red marker in the Tesla app and took the car for a drive as well to make sure to get fresh data.  I looked at a TesalFi API call and I do see the heading is set to null.  _"heading":"",_

Maybe I'll file a bug with James at TeslaFi as likely an issue with my token.  I'd rather not revoke the token at this point as I have some other apps polling.

**Comment by BDubz20** [comment]
Tried Adding another Tesla and get the same data from the API.  Digging in a little further before escalating to James, I found the two Tesla that fail are using API version 67 vs. the working one is version 61.  Subsequently, the heading is returned as a "" in API version 67 vs. null on API version 61 it seems.  

Working: api_version: 61
Not working: api_version: 67

**Comment by jhansche** [comment]
I'm not sure what api_version that is, but it's probably the Tesla API, which TeslaFi is polling. Whether it's null or '' we should still allow for it. The values are not really trustworthy, so the integration should handle it gracefully anyway.

**Comment by BDubz20** [comment]
Confirming the beta works great.  Thank you for investigating and releasing a quick hotfix.

**Comment by jhansche** [comment]
Nice, thanks for confirming!
