### ISSUE TITLE
[Known Issue] Commands unusable

### ISSUE THREAD

**Issue by jhansche** [jhansche/ha-teslafi#13]
Trying to use any command from the TeslaFi API results in this error:

> Tesla Vehicle Command Protocol required, please refer to the documentation here:
> https://developer.tesla.com/docs/fleet-api#2023-11-17-rest-api-vehicle-commands-endpoint-deprecation-timeline-action-required

This is because TeslaFi is not currently using the new Fleet API/SDK. Looks like as of Nov 17, some cars are now no longer able to execute commands over the old REST API.

TeslaFi is currently working on integrating the new Fleet API: https://support.teslafi.com/communities/1/topics/8-changelog#comment-29803. Unfortunately, this error is affecting all commands, including lock/unlock, climate, horn, etc. Hopefully he's making progress on this and will be able to switch over to it soon.

NOTE: there is nothing that we can do here, because the error is coming from Tesla, by way of TeslaFi (they are forwarding the Tesla error back to us). If you want to see progress on this, consider up-voting the comment linked above.

**Comment by jhansche** [comment]
The deprecation notice for Nov-Dec 2023 states:

> REST API support will be [deprecated](https://developer.tesla.com/docs/fleet-api#2023-10-09-rest-api-vehicle-commands-endpoint-deprecation-warning) on existing customer vehicles that have not used the REST API in the preceding 30 days.

So it is possible that only some cars are affected (apparently that includes mine). If you've been using TeslaFi to issue commands - i.e., by setting climate auto preconditioning or something like that - or you had another service that has been issuing commands directly to the Tesla REST API, it is possible that this deprecation has not affected you yet.

**Comment by BDubz20** [comment]
@jhansche are you on the FSD 11.x code branch by chance?  I'm seeing those cars running the older API version from Tesla.

**Comment by jhansche** [comment]
@BDubz20 yeah I am on FSD 11.x

**Comment by jhansche** [comment]
@BDubz20 does that mean that your vehicle uses a newer API and it's still able to execute commands? If so, have you tried redownloading the integration in HACS to test the alarm panel change from #12?

**Comment by jhansche** [comment]
You're right.. I just got the update to 2023.7.12 a few days ago, and now the commands are working, including sentry mode.
