### ISSUE TITLE
How do I display the range in Km rather than miles?

### ISSUE THREAD

**Issue by shallowal** [jhansche/ha-teslafi#23]

**Comment by jurviz** [comment]
... and also the odometer?

**Comment by jhansche** [comment]
The intention was that this would automatically update following your Locale settings - but I just checked myself, and it does not appear to be the case 😬

**Comment by jurviz** [comment]
to circumvent i have a template sensor for the conversion:
{{(states('sensor.a_car_with_no_name_battery_range')|float*1.609344)|round(0,'floor')|int}}

**Comment by jhansche** [comment]
I knew I had seen this somewhere.. according to https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes/ HA _is_ supposed to auto convert.

Maybe I'm missing the right class types or I'm setting the suggested units 🤔

**Comment by Jack-RK-24** [comment]
Same here, distances are shown as „xxx mi“. Do we know if the value from Teslafi coming in isn‘t just a simple string including „ mi“ and not not properly considered as numerical value?

**Comment by jhansche** [comment]
We do know that with 100% certainty. I wrote the integration.

**Comment by jhansche** [comment]
Confirmed fixed by #26:

![Screenshot 2024-03-17 at 3 00 33 PM](https://github.com/jhansche/ha-teslafi/assets/99272/1dff7b7c-b67c-4be3-88f8-05986e0313ec)
