### ISSUE TITLE
start charging ?

### ISSUE THREAD

**Issue by rpaillot** [jhansche/ha-teslafi#27]
Hi there

Stellar work on this HA integration! thank you!
I can unlock doors, make the car honk,  flash lights and wake up but.... didn't find other actions like : start charging, stop charging, activate HVAC , etc... in home assistant.

Although everything is activated in teslafi commands tab.

Anything I missed ? 

Thx again

RP

**Comment by jhansche** [comment]
Closing favor of #28, asking the same question, but with more detail. Please follow that one for updates.
