### ISSUE TITLE
Switch off sentry mode

### ISSUE THREAD

**Issue by snooty83** [jhansche/ha-teslafi#33]
Hello

Activating Sentry Mode works -> Sometimes it stays on the status Activate. But Sentry Mode turns on
You can't turn off Sentry Mode. It always remains to deactivate
I'm using pre-release version 2.5

Greetings Dani

**Comment by jhansche** [comment]
I confirm this is not working as intended. When attempting to disarm while it is armed:
```
2024-04-11 16:53:11.010 DEBUG (MainThread) [custom_components.teslafi] >> executing command set_sentry_mode; args={'sentryMode': False}
2024-04-11 16:53:11.958 DEBUG (MainThread) [custom_components.teslafi] << command set_sentry_mode response: {'response': {'result': True, 'reason': ''}}
```
The TeslaFi command response is showing that it was successful; however, the sentry mode does not change.

I am sending the command the way the TeslaFi API is documented, and the API response shows that it was accepted. However, I do also see that clicking the "Disable Sentry" button on teslafi.com _does work_ correctly. So the TeslaFi website can control it, but it appears that the TeslaFi API is not working.

Have you enabled the Tesla Fleet API token, from https://teslafi.com/tokenNew.php (see Settings > Tesla Account on teslafi.com)?

Also what option is selected under "TeslaFi Controls" section on the same page? Did you enable the TeslaFi Key option?

**Comment by snooty83** [comment]
@jhansche 

Yes, I have activated the new Fleet API.
Here you have an excerpt of my TeslaFI settings.

![image](https://github.com/jhansche/ha-teslafi/assets/51968246/aaa8ffe7-7ea4-4583-98f2-f3d50cac62ff)

Greetings Dani

**Comment by jhansche** [comment]
James at TeslaFi has confirmed that there is an issue on the API side. Will leave this open until it's resolved and confirmed.

**Comment by jhansche** [comment]
TeslaFi reports that this should be resolved now. Can you confirm?

**Comment by snooty83** [comment]
deactivating it now works.
Activating is also possible, but the status remains on Activate.
As I said. Both actually work now, but the integration is not yet 100%

![image](https://github.com/jhansche/ha-teslafi/assets/51968246/67d68a4e-4e40-4ded-aef2-784455253dd6)

**Comment by snooty83** [comment]
@jhansche OK. my internet problem is solved. Sentry mode now works as it should.
Thank you
