### ISSUE TITLE
Sensors Unavailable on v2.7

### ISSUE THREAD

**Issue by TastePurple** [jhansche/ha-teslafi#43]
Using Home Assistant Core 2024.3.3

All switches and binary sensors still function but 'sensor' type entities are no longer reporting.

Logger: homeassistant.setup
Source: setup.py:466
First occurred: July 5, 2024 at 7:08:05 PM (1 occurrences)
Last logged: July 5, 2024 at 7:08:05 PM

Unable to prepare setup for platform 'teslafi.sensor': Platform not found (cannot import name 'override' from 'typing' (/usr/lib/python3.11/typing.py)).

**Comment by jhansche** [comment]
Looks like you're still on Python 3.11. As of HA [2024.2](https://www.home-assistant.io/blog/2024/02/07/release-20242/#shipping-on-a-new-python-version), it ships with 3.12 automatically, and 3.11 [no longer works](https://github.com/home-assistant/architecture/blob/master/adr/0020-minimum-supported-python-version.md) as of HA 2024.4.

I could also add the min Python version in this package, so at least you would get an install-time error if the dependency is not met. But this would not be the first warning you saw for this - you should also be seeing something like this:
![image](https://github.com/user-attachments/assets/1b5fdc82-4a98-44cc-9c6c-7aade702a2f5)

**Comment by jhansche** [comment]
I've updated the min HA version in the HACS manifest (for the next release) to account for this. Thanks for pointing it out.

Please let me know if you're still seeing an issue after updating to Python 3.12 and HA 2024.4.

**Comment by TastePurple** [comment]
Thank you and I appreciate your work. I figured it was the new Python dependency because another HACS plugin prevented me from upgrading but this one did not. For the HA Core users, it's always a bit of an adventure to upgrade Python so I appreciate you adding the version to the manifest. 

No issues on HA 2024.7.2 and Python 3.12.
